- public/agenda.js
- public/bgm.js
- public/firebase/init.js
- public/index.js
- public/timer.js
- public/voice-visualizer.js
> feat(Firestore): Firestore data structure integrated. Any user name will do.

- public/index.html
> fix(stop button): show icon on timer stop button

- public/index.html
- public/index.js
`autofocus` はHTML attrとしてではなく、jQueryで実装してます
> input周りのusabilityを高めた

- README.md
一部`main`に直接書き込んでしまったんだけど、PRとして立てます！
> README.mdに使い方を追加した！

- public/firebase/user-info.js
- public/styles.css
優先順位低いけど気になったからやってしまった。
1. ポップアッププロンプトを使って自分のユーザー名を変更できるようになった！
2. 変更したユーザ名は、Firestore経由で他の参加者にも更新される
> feat(user rename): Now user can rename own user name

- public/firebase/user-info.js
- public/index.html
- public/index.js
- public/reaction.js
- public/styles.css
1. Tensorflowを使うモデルの一つである`BlazeFace`を導入（[本家様](https://github.com/tensorflow/tfjs-models/tree/master/blazeface)）
2. `BlazeFace` で顔の部位の位置（x座標とy座標）をずっと追っていく（いまは右目）
3. 目の動きを時系列データとして取る
4. 「うなずいているとき」に特有の波形を観察して、それを検出する
5. 何度か検出できると、「うなずいた」と判定する
1. ユーザー名を表示する `<p>` タグの上に新しく`<p>` タグを用意した
```html
<p id="local-player-reaction" class="reaction-text">😀</p>
```
2. あわせて、Firestoreの`users` collection に`reaction` というFieldを用意
```
dbRootRef.collection(usersCollection).doc(options.uid.toString()).set({
uid: options.uid,
userName: options.userName,
timeJoined: firebase.firestore.Timestamp.now(),
isActive: true,
reaction: "😀"
}).then(() => 
```
3. リアクションを更新したらJQueryでテキストを更新
4. 更新に合わせてFirestoreの`reaction` fieldも更新　＞＞　更新を検知
> うなずきを検出して表示できるようになった！

- public/index.html
- public/index.js
- public/styles.css
ついでにPublish/Unpublishを知らせるトーストメッセージもつけました
> Unpublish中は諸々いじれないようにした

- dist/index.html
> Add progress bar!

- src/modules/bgm.js
> fix(bgm.js): BGM track "natural" is selected as default when stop button clicked

- src/modules/bgm.js
- src/styles.css
Close #134 
Also some UI improvements:
1. Selector background-color changes when `disabled`
2. playback button is disabled for a while when others changed the BGM.
> fix(bgm): BGM will be played when users join

- README.md
> docs(update README.md): nodding feature section and "upcomings" section

- dist/index.html
- src/styles.css
Add a Buy Me a Coffee button!
fix #28
> feat(buy me a coffee): add a Buy Me a Coffee button

- src/modules/meeting-configuration.js
now we can store users who desires to user Stat! for longer
> fix(extendlimit): await firestore.addDoc()

- src/index.js
This change allows us to make Firebase security rules strict
fix #144
> Firebase-security-rules

- dist/index.html
close #150
1. ロイヤルミルクティーフリーの音源ファイルをダウンロードして
2. クラウドストレージにアップし
3. コピーライト表記を加えた
> chore(bgm rights): copyright text added below the bgm selector

- dist/index.html
- src/index.js
- src/modules/timer.js
- src/styles.css
Close #37 
https://user-images.githubusercontent.com/62736166/133804839-105bbd7f-fdf8-4075-a051-e400876b488d.mov
1. 時間計算をいままでJavascriptのDate()で行っていたのを、FirestoreのTimestamp型に統一
2. 描画処理などごちゃごちゃしていたところをリファクタリング
> Circular Timer

- dist/index.html
- src/index.js
- src/modules/reaction.js
maximum clap count is 5
fix #158
> feat(clap): clap icon appears when user pressed "c"

- dist/index.html
required to use Google Identity
> feat(site verification): add a meta tag for Google Site Verification

- dist/index.html
- src/index.js
You don't have to modify shared url when you're on PR preview or localhost!
> Get-url-dynamically

- dist/index.html
- src/index.js
- src/modules/reaction.js
- src/modules/stat_firebase.js
- src/modules/voice-visualizer.js
- src/styles.css
They return when user left a meeting
fix #172
> Hide privacy policy and terms of service when user joined a meeting

- dist/index.html
- src/index.js
- src/modules/agora.js
- src/modules/stat_auth.js
- src/modules/voice-visualizer.js
Migrating to more secure approach...
> Sign-in-with-redirect

- package-lock.json
- package.json
- src/index.js
- src/modules/meeting-configuration.js
- src/modules/timer.js
- webpack.config.js
file-loader enables webpack to compile sound files
fix #183
> Welcome back, alarm!

- functions/index.js
- functions/package-lock.json
- functions/package.json
- src/index.js
- src/modules/agora.js
- src/modules/stat_firebase.js
Testing migration on Firebase Hosting to avoid CORS block
> Migrate token-generation from Heroku to Firebase (Cloud Functions)

- dist/index.html
- src/index.js
- src/modules/stat_firebase.js
AppCheck is ready to protect our Firebase API key.
> Enable AppCheck

- src/index.js
Enlarge scope for `isTyping`: specific element `#agenda-in` -> `input`
> Disable keypress when typing

- src/index.js
- src/modules/agora.js
- src/modules/reaction.js
- src/modules/stat_firebase.js
- src/modules/utils.js
Fix #199 
I added `await` at `client.subscribe`
It seems just adding `await` before `stat_firebase.init()` in `agora.js` did not fix the issue.
Instead, I modified `try{}...catch{}...finally{}` structure at `stat_firebase.js` which resolved the issue.
I created custom logging function.
Use this for loggings that are not for debugging.
```javascript
export function statConsoleLog(msg) {
console.log(`%cStat! [DEBUG]: %c${msg}`, 'color: #8f35ff', 'color: #0D0D0D');
}
```
> Fix 199: Agora tracks and Firestore timings

- dist/index.html
- dist/signin/index.html
- functions/package-lock.json
- functions/package.json
- package-lock.json
- package.json
- src/index.js
- src/modules/agora.js
- src/modules/stat_auth.js
NG stands for Next Generation (4.x), not "No Good" lol
> Migrate AgoraRTC NG to NPM

- src/index.js
- src/modules/agenda.js
- src/modules/agora.js
- src/modules/bgm.js
- src/modules/reaction.js
- src/modules/stat_auth.js
- src/modules/timer.js
- src/modules/voice-visualizer.js
> Fix two BGM issues
